name: Generate release-artifacts

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          package: 'proz'
          name: 'proz'
          compress: 'true'
          dest: 'dist'
