name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          go build -o dist/proz-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Create Release Artifacts
        run: |
          cd dist
          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip proz-${{ matrix.goos }}-${{ matrix.goarch }}.zip proz-${{ matrix.goos }}-${{ matrix.goarch }}
          else
            tar -czf proz-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz proz-${{ matrix.goos }}-${{ matrix.goarch }}
          fi

      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: proz-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/proz-${{ matrix.goos }}-${{ matrix.goarch }}.*
    
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: proz-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
